export const SIGNING_IN = 'SIGNING_IN',
  AUTH_USER = 'AUTH_USER',
  DEAUTH_USER = 'DEAUTH_USER',
  CREATE_USER = 'CREATE_USER',
  AUTH_ERROR = 'AUTH_ERROR',
  REGISTRATION_ERROR = 'REGISTRATION_ERROR';
